import { FOLDED_DESK_RIDGE_COMPILED_BLOCKOUT } from './sources/folded-desk-ridge.generated';

export const RIDGE_BLOCKOUT_SOURCE = FOLDED_DESK_RIDGE_COMPILED_BLOCKOUT.source;
export const RIDGE_BLOCKOUT_TILE_REGISTRY = FOLDED_DESK_RIDGE_COMPILED_BLOCKOUT.tileRegistry;
export const RIDGE_BLOCKOUT_RUNTIME_TILE_ROOMS =
  FOLDED_DESK_RIDGE_COMPILED_BLOCKOUT.runtimeTileRooms;
export const RIDGE_BLOCKOUT = FOLDED_DESK_RIDGE_COMPILED_BLOCKOUT.map;
