import {
  RIDGE_BLOCKOUT_TRAVERSAL_MOVEMENTS,
  type RidgeBlockoutMap
} from './parser';
import type {
  RidgeBlockoutSource,
  RidgeBlockoutSourceAnchor,
  RidgeBlockoutSourceRect,
  RidgeBlockoutSourceRoom,
  RidgeCompiledBlockout,
  RidgeCompiledBlockoutRoom,
  RidgeTileDefinition,
  RidgeTileRegistry
} from './sourceContract';

class RidgeBlockoutSourceValidationError extends Error {
  readonly errors: readonly string[];

  constructor(errors: readonly string[]) {
    super(`Ridge blockout source validation failed:\n${errors.map((error) => `- ${error}`).join('\n')}`);
    this.name = 'RidgeBlockoutSourceValidationError';
    this.errors = errors;
  }
}

interface TileLookup {
  bySymbol: ReadonlyMap<string, RidgeTileDefinition>;
}

export function compileRidgeBlockoutSource(source: RidgeBlockoutSource): RidgeCompiledBlockout {
  const validationErrors = validateRidgeBlockoutSource(source);
  if (validationErrors.length > 0) {
    throw new RidgeBlockoutSourceValidationError(validationErrors);
  }

  const tileLookup = createTileLookup(source.tileRegistry);
  const map = toRidgeBlockoutMap(source, validationErrors);

  return {
    source,
    map,
    tileRegistry: source.tileRegistry,
    runtimeTileRooms: source.rooms.map((room) => toRuntimeTileRoom(room, tileLookup)),
    validationErrors
  };
}

export function validateRidgeBlockoutSource(source: RidgeBlockoutSource): readonly string[] {
  const errors: string[] = [];
  const tileLookup = validateTileRegistry(source.tileRegistry, errors);
  const roomIds = new Set<string>();

  if (source.language !== 'ridge-v0') {
    errors.push(`unsupported language "${source.language}"`);
  }
  if (!Number.isFinite(source.cell) || source.cell <= 0) {
    errors.push(`invalid cell size "${source.cell}"`);
  }
  if (!source.worldId) {
    errors.push('missing world id');
  }
  if (!source.spawn.roomId || !source.spawn.anchorSymbol) {
    errors.push('missing spawn room or anchor');
  }

  source.rooms.forEach((room) => {
    if (roomIds.has(room.id)) {
      errors.push(`duplicate room "${room.id}"`);
    }
    roomIds.add(room.id);

    validateRoomGrid(room, tileLookup, errors);
    validateRoomAnchors(room, tileLookup, errors);
  });

  validateSpawn(source, roomIds, errors);
  validateRoutes(source, roomIds, errors);
  validateShortcuts(source, roomIds, errors);
  validateRuntimeCellOverlaps(source, tileLookup, errors);

  return errors;
}

function toRidgeBlockoutMap(
  source: RidgeBlockoutSource,
  validationErrors: readonly string[] = validateRidgeBlockoutSource(source)
): RidgeBlockoutMap {
  return {
    language: source.language,
    cell: source.cell,
    worldId: source.worldId,
    title: source.title,
    spawn: source.spawn,
    routes: source.routes.map((route) => ({
      id: route.id,
      roomIds: route.roomIds
    })),
    futureRoutes: (source.futureRoutes ?? []).map((route) => ({
      id: route.id,
      roomIds: route.roomIds
    })),
    shortcuts: (source.shortcuts ?? []).map((shortcut) => ({
      id: shortcut.id,
      fromRoomId: shortcut.fromRoomId,
      toRoomId: shortcut.toRoomId,
      kind: shortcut.kind
    })),
    optionalPockets: (source.optionalPockets ?? []).map((pocket) => ({
      id: pocket.id,
      roomId: pocket.roomId,
      kind: pocket.kind
    })),
    homeMutations: (source.homeMutations ?? []).map((mutation) => ({
      id: mutation.id,
      attrs: mutation.attrs
    })),
    rooms: source.rooms.map((room) => ({
      id: room.id,
      title: room.title,
      place: room.place,
      size: room.size,
      theme: room.theme,
      mood: room.mood,
      links: room.links ?? [],
      props: room.props ?? [],
      grid: room.grid,
      anchors: (room.anchors ?? []).map(toMapAnchor),
      rects: (room.rects ?? []).map(toMapRect),
      declarations: room.declarations ?? []
    })),
    validationErrors
  };
}

export function serializeRidgeCompiledBlockout({
  exportName,
  compiled,
  typeImportPath
}: {
  exportName: string;
  compiled: RidgeCompiledBlockout;
  typeImportPath: string;
}): string {
  return [
    `import type { RidgeCompiledBlockout } from '${typeImportPath}';`,
    '',
    '// This file is generated by scripts/generate-ridge-blockout-sources.mjs.',
    '// Edit the matching .source.ts file instead.',
    '',
    `export const ${exportName} = ` +
      JSON.stringify(compiled, null, 2) +
      ' as const satisfies RidgeCompiledBlockout;',
    ''
  ].join('\n');
}

function validateTileRegistry(
  registry: RidgeTileRegistry,
  errors: string[]
): TileLookup {
  const symbols = new Set<string>();
  const ids = new Set<number>();
  const bySymbol = new Map<string, RidgeTileDefinition>();

  registry.forEach((tile) => {
    if ([...tile.symbol].length !== 1) {
      errors.push(`tile symbol "${tile.symbol}" must be exactly one character`);
    }
    if (symbols.has(tile.symbol)) {
      errors.push(`duplicate tile symbol "${tile.symbol}"`);
    }
    symbols.add(tile.symbol);
    bySymbol.set(tile.symbol, tile);

    if (!Number.isInteger(tile.id) || tile.id < 0) {
      errors.push(`tile "${tile.symbol}" has invalid runtime tile id "${tile.id}"`);
    }
    if (ids.has(tile.id)) {
      errors.push(`duplicate runtime tile id "${tile.id}"`);
    }
    ids.add(tile.id);
  });

  return { bySymbol };
}

function validateRoomGrid(
  room: RidgeBlockoutSourceRoom,
  tileLookup: TileLookup,
  errors: string[]
): void {
  if (room.size.width <= 0 || room.size.height <= 0) {
    errors.push(`room "${room.id}" has invalid size`);
  }
  if (room.grid.length !== room.size.height) {
    errors.push(`room "${room.id}" grid height ${room.grid.length} does not match size ${room.size.height}`);
  }
  room.grid.forEach((row, rowIndex) => {
    if ([...row].length !== room.size.width) {
      errors.push(`room "${room.id}" row ${rowIndex + 1} width ${[...row].length} does not match size ${room.size.width}`);
    }
    [...row].forEach((symbol, columnIndex) => {
      if (!tileLookup.bySymbol.has(symbol)) {
        errors.push(`room "${room.id}" has unknown symbol "${symbol}" at ${columnIndex},${rowIndex}`);
      }
    });
  });
}

function validateRoomAnchors(
  room: RidgeBlockoutSourceRoom,
  tileLookup: TileLookup,
  errors: string[]
): void {
  (room.anchors ?? []).forEach((anchor) => {
    if (!tileLookup.bySymbol.has(anchor.symbol)) {
      errors.push(`room "${room.id}" anchor "${anchor.symbol}" uses an unknown tile symbol`);
    }
    if (!room.grid.some((row) => [...row].includes(anchor.symbol))) {
      errors.push(`room "${room.id}" anchor "${anchor.symbol}" has no matching grid cell`);
    }
    if (
      anchor.attrs?.movement !== undefined &&
      !RIDGE_BLOCKOUT_TRAVERSAL_MOVEMENTS.has(anchor.attrs.movement)
    ) {
      errors.push(
        `room "${room.id}" anchor "${anchor.symbol}" has unknown movement "${anchor.attrs.movement}"`
      );
    }
  });
}

function validateSpawn(
  source: RidgeBlockoutSource,
  roomIds: ReadonlySet<string>,
  errors: string[]
): void {
  if (!roomIds.has(source.spawn.roomId)) {
    errors.push(`spawn room "${source.spawn.roomId}" does not exist`);
    return;
  }

  const spawnRoom = source.rooms.find((room) => room.id === source.spawn.roomId);
  const spawnAnchor = spawnRoom?.anchors?.find((anchor) =>
    anchor.symbol === source.spawn.anchorSymbol
  );
  if (!spawnAnchor) {
    errors.push(`spawn anchor "${source.spawn.anchorSymbol}" does not exist in room "${source.spawn.roomId}"`);
  }
}

function validateRoutes(
  source: RidgeBlockoutSource,
  roomIds: ReadonlySet<string>,
  errors: string[]
): void {
  [...source.routes, ...(source.futureRoutes ?? [])].forEach((route) => {
    route.roomIds.forEach((roomId) => {
      if (!roomIds.has(roomId)) {
        errors.push(`route "${route.id}" references missing room "${roomId}"`);
      }
    });
  });
}

function validateShortcuts(
  source: RidgeBlockoutSource,
  roomIds: ReadonlySet<string>,
  errors: string[]
): void {
  (source.shortcuts ?? []).forEach((shortcut) => {
    if (!roomIds.has(shortcut.fromRoomId)) {
      errors.push(`shortcut "${shortcut.id}" references missing from room "${shortcut.fromRoomId}"`);
    }
    if (!roomIds.has(shortcut.toRoomId)) {
      errors.push(`shortcut "${shortcut.id}" references missing to room "${shortcut.toRoomId}"`);
    }
  });
}

function validateRuntimeCellOverlaps(
  source: RidgeBlockoutSource,
  tileLookup: TileLookup,
  errors: string[]
): void {
  const seen = new Map<string, { roomId: string; symbol: string }>();

  source.rooms.forEach((room) => {
    room.grid.forEach((row, rowIndex) => {
      [...row].forEach((symbol, columnIndex) => {
        const tile = tileLookup.bySymbol.get(symbol);
        if (!tile || !isRuntimeActiveTile(tile)) return;

        const key = `${room.place.x + columnIndex},${room.place.y + rowIndex}`;
        const previous = seen.get(key);
        if (previous && previous.roomId !== room.id) {
          errors.push(
            `runtime cell overlap at ${key}: ${previous.roomId}/${previous.symbol} and ${room.id}/${symbol}`
          );
          return;
        }
        seen.set(key, { roomId: room.id, symbol });
      });
    });
  });
}

function createTileLookup(registry: RidgeTileRegistry): TileLookup {
  return {
    bySymbol: new Map(registry.map((tile) => [tile.symbol, tile]))
  };
}

function toRuntimeTileRoom(
  room: RidgeBlockoutSourceRoom,
  tileLookup: TileLookup
): RidgeCompiledBlockoutRoom {
  return {
    id: room.id,
    runtimeTileRows: room.grid.map((row) =>
      [...row].map((symbol) => tileLookup.bySymbol.get(symbol)?.id ?? -1)
    )
  };
}

function toMapAnchor(anchor: RidgeBlockoutSourceAnchor) {
  return {
    symbol: anchor.symbol,
    kind: anchor.kind,
    attrs: anchor.attrs ?? {}
  };
}

function toMapRect(rect: RidgeBlockoutSourceRect) {
  return {
    id: rect.id,
    x: rect.x,
    y: rect.y,
    width: rect.width,
    height: rect.height,
    attrs: rect.attrs ?? {}
  };
}

function isRuntimeActiveTile(tile: RidgeTileDefinition): boolean {
  if (tile.runtimeActive !== undefined) return tile.runtimeActive;
  return tile.kind !== 'empty' && tile.kind !== 'design' && tile.kind !== 'ladder';
}
