export const INITIAL_PREVIEW_ZOOM = 1;

export const PREVIEW_ZOOM_OPTIONS = [0.65, 0.75, 1, 1.25, 1.5, 1.6] as const;

export const PREVIEW_ZOOM_MIN = PREVIEW_ZOOM_OPTIONS[0];
export const PREVIEW_ZOOM_MAX = PREVIEW_ZOOM_OPTIONS[PREVIEW_ZOOM_OPTIONS.length - 1];

export const PLAYER_SNAPSHOT_RENDER_INTERVAL_MS = 250;
